### PR TITLE
fix arg name in error message

### PR DESCRIPTION
**Pull request by rstory**
found this while debuggin 3.6.7 issues

### CODE REVIEW

**Comment by mykaul** [comment]
@tiraboschi  - pleaes have a look.
@rstory  - many thanks for the patch. However, this is a read-only copy of our repository.
Please see http://www.ovirt.org/develop/dev-process/working-with-gerrit/ on how to contribute via Gerrit.
Let me know if I can help you with the process!

**Comment by tiraboschi** [comment]
Thanks for your patch Robert,
I'll open a proper bug and I'll re-submit your patch on our gerrit repo.

**Review by nirs — APPROVED** [review]
Looks good.

**Comment by sandrobonazzola** [comment]
@tiraboschi is this patch pushed in gerrit? can we close this pull request?

**Comment by jack17529** [comment]
Anyone working on conflicts?

**Comment by mykaul** [comment]
@rstory - will you be able to resolve the conflict and push?

**Comment by eedri** [comment]
I don't think its possible to submit patches to the project via github since the project is maintained on gerrit.ovirt.org.
This repo is a read only sync from Gerrit, to run integration with travis, docs,etc...

**Comment by jack17529** [comment]
@mykaul I would have solved but I have no wright permissions

**Comment by tiraboschi** [comment]
It's here: https://gerrit.ovirt.org/#/c/67539/4 let's close

**Comment by eedri** [comment]
duplicate of https://gerrit.ovirt.org/#/c/67539/4

**Pull request closed without merging**
