### PR TITLE
cpu_load_no_engine: Use cpuActual from vdsm

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Import from gerrit: https://gerrit.ovirt.org/c/ovirt-hosted-engine-ha/+/117964
as submitted by @didib 

```
Use [1]. Keep compatibility with older vdsm.

[1] https://gerrit.ovirt.org/c/vdsm/+/117869
Change Id I5adb1b01653b0029a30949ecb89219fde794dfd8

Related-To: https://bugzilla.redhat.com/2026263
Change-Id: Ifba124aea5973b8a2ce362f2c18f5affa7e7e897
Signed-off-by: Yedidyah Bar David <didi@redhat.com>
```

### CODE REVIEW

**Review by mz-pdm — APPROVED** [review]

**Comment by sandrobonazzola** [comment]
@didib can you please verify?

**Comment by didib** [comment]
Ran https://redir.apps.ovirt.org/dj/job/ds-ost-baremetal_manual/33867/ for sanity testing.
Considering that bz 2026263 is VERIFIED and that we never managed to reproduce bz 1993957, I hope this is enough.

**Comment by didib** [comment]
From above jenkins run, on host-0 (still running):

[root@ost-he-basic-suite-master-host-0 ~]# grep -i cpu /var/log/ovirt-hosted-engine-ha/broker.log 
MainThread::INFO::2022-04-14 07:06:18,704::monitor::62::ovirt_hosted_engine_ha.broker.monitor.Monitor::(_discover_submonitors) Loaded submonitor cpu-load
MainThread::INFO::2022-04-14 07:06:18,708::monitor::62::ovirt_hosted_engine_ha.broker.monitor.Monitor::(_discover_submonitors) Loaded submonitor cpu-load-no-engine
MainThread::INFO::2022-04-14 07:06:45,259::monitor::62::ovirt_hosted_engine_ha.broker.monitor.Monitor::(_discover_submonitors) Loaded submonitor cpu-load
MainThread::INFO::2022-04-14 07:06:45,269::monitor::62::ovirt_hosted_engine_ha.broker.monitor.Monitor::(_discover_submonitors) Loaded submonitor cpu-load-no-engine
Listener::INFO::2022-04-14 07:07:05,382::monitor::80::ovirt_hosted_engine_ha.broker.monitor.Monitor::(start_submonitor) Starting submonitor cpu-load-no-engine
Listener::INFO::2022-04-14 07:07:05,382::monitor::91::ovirt_hosted_engine_ha.broker.monitor.Monitor::(start_submonitor) Started submonitor cpu-load-no-engine
Thread-4::INFO::2022-04-14 07:07:15,481::cpu_load_no_engine::123::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) VM not on this host
Thread-4::INFO::2022-04-14 07:07:15,481::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.6351, engine=0.0000, non-engine=0.6351
Thread-4::INFO::2022-04-14 07:08:15,548::cpu_load_no_engine::123::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) VM not on this host
Thread-4::INFO::2022-04-14 07:08:15,549::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.6771, engine=0.0000, non-engine=0.6771
Thread-4::INFO::2022-04-14 07:09:25,039::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.9231, engine=0.4591, non-engine=0.4641
Thread-4::INFO::2022-04-14 07:10:25,913::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=1.0000, engine=0.4492, non-engine=0.5508
Thread-4::INFO::2022-04-14 07:11:35,611::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.9996, engine=0.4647, non-engine=0.5349
Thread-4::INFO::2022-04-14 07:12:45,032::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.9901, engine=0.4081, non-engine=0.5821
Thread-4::INFO::2022-04-14 07:13:45,241::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.9917, engine=0.5250, non-engine=0.4667
Thread-4::INFO::2022-04-14 07:14:49,032::cpu_load_no_engine::158::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) Ignoring cpuUser/cpuSys, init values
Thread-4::INFO::2022-04-14 07:15:55,113::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.6674, engine=0.0856, non-engine=0.5817
Thread-4::INFO::2022-04-14 07:16:55,183::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.5506, engine=0.3614, non-engine=0.1892
Thread-4::INFO::2022-04-14 07:17:55,264::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.5756, engine=0.3401, non-engine=0.2355
Thread-4::INFO::2022-04-14 07:18:55,336::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4054, engine=0.2576, non-engine=0.1479
Thread-4::INFO::2022-04-14 07:19:55,406::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4332, engine=0.2936, non-engine=0.1396
Thread-4::INFO::2022-04-14 07:20:55,512::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4005, engine=0.1785, non-engine=0.2220
Thread-4::INFO::2022-04-14 07:21:55,610::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4747, engine=0.4096, non-engine=0.0652
Thread-4::INFO::2022-04-14 07:22:55,730::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4248, engine=0.2681, non-engine=0.1567
Thread-4::INFO::2022-04-14 07:23:55,819::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.5252, engine=0.3821, non-engine=0.1431
Thread-4::INFO::2022-04-14 07:24:56,005::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.6892, engine=0.1416, non-engine=0.5476
Thread-4::INFO::2022-04-14 07:25:56,075::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.3680, engine=0.1240, non-engine=0.2440
Thread-4::INFO::2022-04-14 07:26:56,145::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.3840, engine=0.1154, non-engine=0.2686
Thread-4::INFO::2022-04-14 07:27:56,226::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4999, engine=0.4912, non-engine=0.0087
Thread-4::INFO::2022-04-14 07:28:56,432::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.5241, engine=0.5112, non-engine=0.0128
Thread-4::INFO::2022-04-14 07:29:56,507::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.5474, engine=0.1932, non-engine=0.3543
Thread-4::INFO::2022-04-14 07:30:56,588::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.3823, engine=0.1943, non-engine=0.1881
Thread-4::INFO::2022-04-14 07:31:56,652::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.4684, engine=0.2920, non-engine=0.1764
Thread-4::INFO::2022-04-14 07:32:56,733::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.3839, engine=0.2199, non-engine=0.1640

Looks ok to me.

**Comment by didib** [comment]
I also checked on host-1, changing /etc/ovirt-hosted-engine-ha/broker-log.conf to log at DEBUG level, that I get:
```
[root@ost-he-basic-suite-master-host-1 ~]# grep -i cpu /var/log/ovirt-hosted-engine-ha/broker.log | tail -10
Thread-4::DEBUG::2022-04-14 07:35:24,971::cpu_load_no_engine::134::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) cpu_data_is_real: False
Thread-4::INFO::2022-04-14 07:35:24,971::cpu_load_no_engine::142::cpu_load_no_engine.CpuLoadNoEngine::(calculate_load) System load total=0.2364, engine=0.0000, non-engine=0.2364
Listener::DEBUG::2022-04-14 07:35:25,893::listener::103::ovirt_hosted_engine_ha.broker.listener.Action.status_monitor::(wrapper) Executing RPC handler status_monitor with params (<ovirt_hosted_engine_ha.broker.listener.ActionsHandler object at 0x7f22b0c5d828>, 'cpu-load-no-engine')
Listener::DEBUG::2022-04-14 07:35:25,893::monitor::137::ovirt_hosted_engine_ha.broker.monitor.Monitor::(get_value) Submonitor cpu-load-no-engine current value: 0.2364
Listener::DEBUG::2022-04-14 07:35:36,376::listener::103::ovirt_hosted_engine_ha.broker.listener.Action.status_monitor::(wrapper) Executing RPC handler status_monitor with params (<ovirt_hosted_engine_ha.broker.listener.ActionsHandler object at 0x7f22b0c5d828>, 'cpu-load-no-engine')
Listener::DEBUG::2022-04-14 07:35:36,376::monitor::137::ovirt_hosted_engine_ha.broker.monitor.Monitor::(get_value) Submonitor cpu-load-no-engine current value: 0.2364
Listener::DEBUG::2022-04-14 07:35:46,781::listener::103::ovirt_hosted_engine_ha.broker.listener.Action.status_monitor::(wrapper) Executing RPC handler status_monitor with params (<ovirt_hosted_engine_ha.broker.listener.ActionsHandler object at 0x7f22b0c5d828>, 'cpu-load-no-engine')
Listener::DEBUG::2022-04-14 07:35:46,781::monitor::137::ovirt_hosted_engine_ha.broker.monitor.Monitor::(get_value) Submonitor cpu-load-no-engine current value: 0.2364
Listener::DEBUG::2022-04-14 07:35:56,253::listener::103::ovirt_hosted_engine_ha.broker.listener.Action.status_monitor::(wrapper) Executing RPC handler status_monitor with params (<ovirt_hosted_engine_ha.broker.listener.ActionsHandler object at 0x7f22b0c5d828>, 'cpu-load-no-engine')
Listener::DEBUG::2022-04-14 07:35:56,253::monitor::137::ovirt_hosted_engine_ha.broker.monitor.Monitor::(get_value) Submonitor cpu-load-no-engine current value: 0.2364
```

**Comment by didib** [comment]
Job finished successfully, logs looks ok. Looks safe to merge.

**Pull request merged**
